### ISSUE TITLE
Uh....

### ISSUE THREAD

**Issue by TrickJoker312** [OutRed/outred.github.io#32]
...

**Comment by TrickJoker312** [comment]
One sec, gotta send the picture...

**Comment by TrickJoker312** [comment]
ok, doesn't work. I'll just tell you. I went to click on the site, and it said it detects a "Deceptive Site". Is this a glitch, or are you up to something suspicious?

**Comment by OutRed** [comment]
I think it’s because I’ve added something to my nav that doesn’t work because I haven’t finished it. I assure you I’m not a scammer lolSent from my iPhoneOn Feb 15, 2023, at 6:59 AM, TrickJoker ***@***.***> wrote:﻿
ok, doesn't work. I'll just tell you. I went to click on the site, and it said it detects a "Deceptive Site". Is this a glitch, or are you up to something suspicious?
